
import Project.ConnectionProvider;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class menupage extends javax.swing.JFrame {

    /**
     * Creates new form menupage
     */
    public menupage() {
        initComponents();
       // setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnLogout = new javax.swing.JButton();
        jBtnReturnbook = new javax.swing.JButton();
        jBtnIssuebok = new javax.swing.JButton();
        jBtnStat = new javax.swing.JButton();
        jBtnNewbook = new javax.swing.JButton();
        jBtnNewstudent = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bkSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnLogout.setBackground(new java.awt.Color(204, 204, 204));
        jBtnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jBtnLogout.setText("Log Out");
        jBtnLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 310, 130));

        jBtnReturnbook.setBackground(new java.awt.Color(204, 204, 204));
        jBtnReturnbook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReturnbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return book.png"))); // NOI18N
        jBtnReturnbook.setText("Return Book");
        jBtnReturnbook.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnReturnbook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnReturnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReturnbookActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnReturnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 300, 140));

        jBtnIssuebok.setBackground(new java.awt.Color(204, 204, 204));
        jBtnIssuebok.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnIssuebok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issue book.png"))); // NOI18N
        jBtnIssuebok.setText("Issue Book");
        jBtnIssuebok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnIssuebok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnIssuebok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIssuebokActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIssuebok, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 300, -1));

        jBtnStat.setBackground(new java.awt.Color(204, 204, 204));
        jBtnStat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnStat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/statistics.png"))); // NOI18N
        jBtnStat.setText("Statistics");
        jBtnStat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnStat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStatActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 300, 130));

        jBtnNewbook.setBackground(new java.awt.Color(204, 204, 204));
        jBtnNewbook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnNewbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add book.png"))); // NOI18N
        jBtnNewbook.setText("New Book");
        jBtnNewbook.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnNewbook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnNewbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNewbookActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNewbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 290, 140));

        jBtnNewstudent.setBackground(new java.awt.Color(204, 204, 204));
        jBtnNewstudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnNewstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/member.png"))); // NOI18N
        jBtnNewstudent.setText("New Student");
        jBtnNewstudent.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnNewstudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnNewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNewstudentActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNewstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 290, 135));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchstudent.png"))); // NOI18N
        jButton1.setText("Search Student");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 310, 130));

        bkSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bkSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksearch.png"))); // NOI18N
        bkSearch.setText("BOOK SEARCH");
        bkSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bkSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkSearchActionPerformed(evt);
            }
        });
        getContentPane().add(bkSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 310, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menupagebg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1590, 0, 3220, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNewbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNewbookActionPerformed
        setVisible(false);
        new newBook().setVisible(true);
        
    }//GEN-LAST:event_jBtnNewbookActionPerformed

    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jBtnLogoutActionPerformed

    private void jBtnNewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNewstudentActionPerformed
        setVisible(false);
        new newStudent().setVisible(true);
    }//GEN-LAST:event_jBtnNewstudentActionPerformed

    private void jBtnIssuebokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIssuebokActionPerformed
        setVisible(false);
        new issueBook().setVisible(true);       
     
    }//GEN-LAST:event_jBtnIssuebokActionPerformed

    private void jBtnReturnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReturnbookActionPerformed
        setVisible(false);
        new returnBook().setVisible(true);
    }//GEN-LAST:event_jBtnReturnbookActionPerformed

    private void jBtnStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStatActionPerformed
        setVisible(false);
       new statistics().setVisible(true);
                
    }//GEN-LAST:event_jBtnStatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new studentSearch().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bkSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkSearchActionPerformed
       setVisible(false);
       new bookSearch().setVisible(true);
    }//GEN-LAST:event_bkSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menupage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkSearch;
    private javax.swing.JButton jBtnIssuebok;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JButton jBtnNewbook;
    private javax.swing.JButton jBtnNewstudent;
    private javax.swing.JButton jBtnReturnbook;
    private javax.swing.JButton jBtnStat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
