import java.sql.*;
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class newBook extends javax.swing.JFrame {

    /**
     * Creates new form newBook
     */
    public newBook() {
        initComponents();
        this.setLocationRelativeTo(null);
       // setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkName = new javax.swing.JTextField();
        bkWriter = new javax.swing.JTextField();
        bkPrice = new javax.swing.JTextField();
        bkPbyear = new javax.swing.JTextField();
        bkId = new javax.swing.JTextField();
        bkType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bkName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bkName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 257, 30));

        bkWriter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bkWriter, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 257, 30));

        bkPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bkPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 257, 30));

        bkPbyear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bkPbyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 257, 30));

        bkId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bkId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 257, 30));

        bkType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bkType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physics", "Chemistry", "Mathematics", "Electronics", "Computer Science", "IPE&ME", "Textile", "Others" }));
        getContentPane().add(bkType, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 257, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Book ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 131, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Book Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 131, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Writer:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 131, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Price:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 131, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Publishing year:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Book type:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 131, -1));

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        save.setText("SAVE");
        save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 637, 150, 60));

        cancel.setBackground(new java.awt.Color(204, 204, 204));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        cancel.setText("CANCEL");
        cancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 637, 160, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newbookbg3.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        setVisible(false);
        new menupage().setVisible(true);
        
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String bookId = bkId.getText();
        String bookName=bkName.getText();
        String bookWriter=bkWriter.getText();
        String bookPrice=bkPrice.getText();
        String publishingYear=bkPbyear.getText();
        String bookType=(String)bkType.getSelectedItem();
        boolean publishingyear = true;
        boolean bookprice = true;
        for (int i = 0; i < bookPrice.length(); i++) {

            if (!(bookPrice.charAt(i) >= '0' && bookPrice.charAt(i) <= '9')) {

              bookprice = false;
               
                JOptionPane.showMessageDialog(null,"Book Price is invalid");

                return;

            }

        }
        for (int i = 0; i < publishingYear.length(); i++) {

            if (!(publishingYear.charAt(i) >= '0' && publishingYear.charAt(i) <= '9')) {

               publishingyear = false;
               
                JOptionPane.showMessageDialog(null,"Publishing Year is invalid");

                return;

            }

        }
         
        try
        {
            if(bkId.getText().equals("") || bkName.getText().equals("") || bkWriter.getText().equals("") || bkPrice.getText().equals("") || bkPbyear.getText().equals(""))
            {
                
                JOptionPane.showMessageDialog(null, "field must not be empty");
                
                return;
            }
            else{
                
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("Insert Into newbook VALUES ('"+bookId+"','"+bookName+"','"+bookWriter+"','"+bookPrice+"','"+publishingYear+"','"+bookType+"')");
            JOptionPane.showMessageDialog(null,"Successfully updated");
            setVisible(false);
            new newBook().setVisible(true);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Book ID already exists");
            setVisible(false);
            new newBook().setVisible(true);
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bkId;
    private javax.swing.JTextField bkName;
    private javax.swing.JTextField bkPbyear;
    private javax.swing.JTextField bkPrice;
    private javax.swing.JComboBox<String> bkType;
    private javax.swing.JTextField bkWriter;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
