
import java.sql.*;
import Project.ConnectionProvider;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class newStudent extends javax.swing.JFrame {

    public newStudent() {
        initComponents();
        this.setLocationRelativeTo(null);
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stdId = new javax.swing.JTextField();
        stdName = new javax.swing.JTextField();
        fthrName = new javax.swing.JTextField();
        mthrName = new javax.swing.JTextField();
        emailId = new javax.swing.JTextField();
        phnNmbr = new javax.swing.JTextField();
        dptCmbbox = new javax.swing.JComboBox<>();
        jBtnSave = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("STUDENT ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setText("STUDENT NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setText("FATHER'S NAME:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setText("MOTHER'S NAME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setText("E-MAIL ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setText("PHONE NUMBER:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setText("DEPARTMENT:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        stdId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(stdId, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 133, 300, 30));

        stdName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(stdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 193, 300, 30));

        fthrName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(fthrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 253, 300, 30));

        mthrName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(mthrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 303, 300, 30));

        emailId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 300, 30));

        phnNmbr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(phnNmbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 300, 30));

        dptCmbbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dptCmbbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "CIVIL", "EEE", "ME", "TE", "ARCH", "BBA", " " }));
        getContentPane().add(dptCmbbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 300, 30));

        jBtnSave.setBackground(new java.awt.Color(204, 204, 204));
        jBtnSave.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jBtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jBtnSave.setText("SAVE");
        jBtnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 140, 60));

        jBtnCancel.setBackground(new java.awt.Color(204, 204, 204));
        jBtnCancel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jBtnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        jBtnCancel.setText("CANCEL");
        jBtnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 150, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/returnbookbg.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed

        setVisible(false);
        new menupage().setVisible(true);

    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        String studentID = stdId.getText();
        String studentName = stdName.getText();
        String fatherName = fthrName.getText();
        String motherName = mthrName.getText();
        String emailID = emailId.getText();
        String phoneNumber = phnNmbr.getText();
        String department = (String) dptCmbbox.getSelectedItem();
        boolean mailFormat = Pattern.matches("[^.\\s][a-z0-9\\.\\_]{3,64}@([a-z]){2,50}.[a-z]{2,}", emailID);
        boolean phoneFormat = Pattern.matches("[^.\\s][0-9]{11,}", phoneNumber);
        boolean studentname = true;
        boolean studentid = true;
        for (int i = 0; i < studentID.length(); i++) {

            if (!(studentID.charAt(i) >= '0' && studentID.charAt(i) <= '9')) {

                studentid = false;
                JOptionPane.showMessageDialog(null, "Student id invalid");

                return;

            }

        }
        for (int i = 0; i < studentName.length(); i++) {

            if ((studentName.charAt(i) >= '0' && studentName.charAt(i) <= '9')) {

                studentname = false;

                JOptionPane.showMessageDialog(null, "Student name invalid");

                return;

            }

        }

        try {
            if (stdId.getText().equals("") || stdName.getText().equals("") || fthrName.getText().equals("") || mthrName.getText().equals("") || emailId.getText().equals("") || phnNmbr.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "field must not be empty");
            } else {
                if (mailFormat && phoneFormat) {

                    Connection con = ConnectionProvider.getCon();
                    Statement st = con.createStatement();
                    st.executeUpdate("Insert Into studentinfo VALUES ('" + studentID + "','" + studentName + "','" + fatherName + "','" + motherName + "','" + emailID + "','" + phoneNumber + "','" + department + "')");
                    JOptionPane.showMessageDialog(null, "Successfully updated");
                    setVisible(false);
                    new newStudent().setVisible(true);

                } else if (!mailFormat) {

                    JOptionPane.showMessageDialog(null, "email format invalid");

                } else if (!phoneFormat) {

                    JOptionPane.showMessageDialog(null, "phone format invalid");

                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Student ID already exists");
            setVisible(false);
            new newStudent().setVisible(true);
        }
    }//GEN-LAST:event_jBtnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dptCmbbox;
    private javax.swing.JTextField emailId;
    private javax.swing.JTextField fthrName;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mthrName;
    private javax.swing.JTextField phnNmbr;
    private javax.swing.JTextField stdId;
    private javax.swing.JTextField stdName;
    // End of variables declaration//GEN-END:variables
}
