
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class register extends javax.swing.JFrame {


    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    Connection connection = null;
    
    public void reset()
    {
        Name.setText("");
        Username.setText("");
        password1.setText("");
        password2.setText("");
        Email.setText("");
        number.setText("");
        Address.setText("");
    }
    
    
    public boolean verifyFields()
    {
        String NAME = Name.getText();
        String USERNAME =Username.getText();
        String PASSWORD = String.valueOf(password1.getPassword());
        String CONFIRMPASS = String.valueOf(password2.getPassword());
        String EMAIL = Email.getText();
        String PHONE = number.getText();
        String ADDRESS = Address.getText();
        
        if(NAME.trim().equals("") || USERNAME.trim().equals("") || PASSWORD.trim().equals("") || CONFIRMPASS.trim().equals("") || 
                EMAIL.trim().equals("") || PHONE.trim().equals("") || ADDRESS.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or more Fields are Empty", "Empty Fields",2);
            return false;
        }
        else{
            return true; 
        }
    }
    
    public void validPassword()
    {
        String pass = password1.getText();
        String pass2 = password2.getText();
        
        if(!pass.equals(pass2))
        {
            JOptionPane.showMessageDialog(this, "The Password does not match, please check again!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBtnsubmit = new javax.swing.JButton();
        jBtnreset = new javax.swing.JButton();
        jBtnclose = new javax.swing.JButton();
        Username = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REGISTER FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 55, -1, 43));

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 164, 359, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 155, 126, 38));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("User Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 211, 126, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 260, 106, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Confirm Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 316, 181, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("E-mail:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 378, 113, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Phone Number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 438, 171, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 494, 133, -1));

        jBtnsubmit.setBackground(new java.awt.Color(153, 204, 255));
        jBtnsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jBtnsubmit.setText("Submit");
        jBtnsubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnsubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, 130, 60));

        jBtnreset.setBackground(new java.awt.Color(153, 204, 255));
        jBtnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.jpg"))); // NOI18N
        jBtnreset.setText("Reset");
        jBtnreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnresetActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 130, 60));

        jBtnclose.setBackground(new java.awt.Color(153, 204, 255));
        jBtnclose.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jBtnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jBtnclose.setText("Back");
        jBtnclose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtncloseActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, 130, 60));

        Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 212, 359, -1));

        Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 379, 362, -1));

        number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberKeyTyped(evt);
            }
        });
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 439, 366, -1));

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 495, 366, -1));

        password1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 261, 359, -1));

        password2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                password2FocusLost(evt);
            }
        });
        getContentPane().add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 317, 362, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registration.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 890, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jBtnresetActionPerformed

    private void jBtncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtncloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jBtncloseActionPerformed

    private void jBtnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnsubmitActionPerformed
        // TODO add your handling code here
        validPassword();
        verifyFields();
        
        String name = Name.getText();
        String username =Username.getText();
        String password = String.valueOf(password1.getPassword());
        String confirmpassword = String.valueOf(password2.getPassword());
        String email = Email.getText();
        String phonenumber = number.getText();
        String address = Address.getText();
        
        boolean mailFormat = Pattern.matches("[^.\\s][a-z0-9\\.\\_]{3,64}@([a-z]){2,50}.[a-z]{2,}", email);
        boolean phoneFormat = Pattern.matches("[0-9]{11,}", phonenumber);
        boolean userName = true;
        boolean Name = true;
        boolean Address = true;
        
        
        for (int i=0; i<username.length(); i++) {

            if ((username.charAt(i) >= '0' && username.charAt(i) <= '9')) {

                userName=false;

                JOptionPane.showMessageDialog(null, "User name Invalid");

                return;
            }
        }
        for (int i=0; i<name.length(); i++) {

            if ((name.charAt(i) >= '0' && name.charAt(i) <= '9')) {

                Name=false;

                JOptionPane.showMessageDialog(null, "Name is Invalid");

                return;
            }
        }
        for (int i=0; i<address.length(); i++) {

            if ((address.charAt(i) >= '0' && address.charAt(i) <= '9')) {

                Address=false;

                JOptionPane.showMessageDialog(null, "Address is Invalid");

                return;
            }
        }
      
        try{
            if (mailFormat && phoneFormat) {
                
            
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("INSERT Into register VALUES ('"+name+"','"+username+"','"+password+"','"+confirmpassword+"','"+email+"', '"+phonenumber+"','"+address+"')");
            JOptionPane.showMessageDialog(this, "Record save successfully");
            
            setVisible(false);
        new login().setVisible(true);
            } else if (!mailFormat) 
                    {
                JOptionPane.showMessageDialog(null, "Email format invalid");
                
            } else if (!phoneFormat) {
                JOptionPane.showMessageDialog(null, "Phone format invalid");
            }
        
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "User name already exists");
        }
    }//GEN-LAST:event_jBtnsubmitActionPerformed

    private void password2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password2FocusLost
        // TODO add your handling code here:
        validPassword();
    }//GEN-LAST:event_password2FocusLost

    private void numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_numberKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Username;
    private javax.swing.JButton jBtnclose;
    private javax.swing.JButton jBtnreset;
    private javax.swing.JButton jBtnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField number;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    // End of variables declaration//GEN-END:variables

    private Object login() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
