import java.sql.*;
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class returnBook extends javax.swing.JFrame {

    /**
     * Creates new form returnBook
     */
    public returnBook() {
        initComponents();
        this.setLocationRelativeTo(null);
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bkID = new javax.swing.JTextField();
        stdID = new javax.swing.JTextField();
        saveDatabtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        issueDate = new javax.swing.JTextField();
        returnDate = new javax.swing.JTextField();
        saveBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BOOK ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("STUDENT ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ISSUE DATE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("RETURN DATE:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, -1));

        bkID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(bkID, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 210, 40));

        stdID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(stdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 210, 40));

        saveDatabtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveDatabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        saveDatabtn.setText("SAVE");
        saveDatabtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveDatabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveDatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDatabtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveDatabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 150, 60));

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchBtn.setText("SEARCH");
        searchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, 150, 60));

        closeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        closeBtn.setText("CLOSE");
        closeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 560, 150, 60));

        issueDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        issueDate.setEnabled(false);
        getContentPane().add(issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 210, 40));

        returnDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        returnDate.setEnabled(false);
        returnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDateActionPerformed(evt);
            }
        });
        getContentPane().add(returnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, 210, 40));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/returnbook 4.jpg"))); // NOI18N
        saveBtn.setText("jLabel5");
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveDatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDatabtnActionPerformed

         String bookID=bkID.getText();
        String studentID=stdID.getText();
        
        
        boolean studentid = true;
        for (int i = 0; i < studentID.length(); i++) {

            if (!(studentID.charAt(i) >= '0' && studentID.charAt(i) <= '9')) {

                studentid = false;

                JOptionPane.showMessageDialog(null, "Student id is invalid");

                return;

            }

        }
        try
        {
            if(bkID.getText().equals("") || stdID.getText().equals(""))
             {
                 
             JOptionPane.showMessageDialog(null, "field must not be empty");
             
             return;
            
             }
         Connection con= ConnectionProvider.getCon();
         Statement st=con.createStatement();
         st.executeUpdate("update issuedbooks set Return_Book='YES' where Book_ID='"+bookID+"'and Student_ID='"+studentID+"'");
         JOptionPane.showMessageDialog(null, "Book Successfully Returned");
         setVisible(false);
         new returnBook().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
        
    }//GEN-LAST:event_saveDatabtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
       setVisible(false);
       new menupage().setVisible(true);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void returnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnDateActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        
        String bookID=bkID.getText();
        String studentID=stdID.getText();
        try
        {
             
             
         Connection con= ConnectionProvider.getCon();
         Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("Select *from issuedbooks where Book_ID='"+bookID+"'and Student_ID='"+studentID+"'");
         if(rs.next())
         {
             issueDate.setText(rs.getString(3));
             returnDate.setText(rs.getString(4));
             bkID.setEditable(false);
             stdID.setEditable(false);
             
         }
         else
         {
           
            JOptionPane.showMessageDialog(null, "Incorrect Student ID or Incorrect Book ID");
            setVisible(false);
            new returnBook().setVisible(true);
            
         }
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, "Connection Error"); 
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bkID;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField issueDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField returnDate;
    private javax.swing.JLabel saveBtn;
    private javax.swing.JButton saveDatabtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField stdID;
    // End of variables declaration//GEN-END:variables
}
