import java.sql.*;
import Project.ConnectionProvider;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class statistics extends javax.swing.JFrame {

    /**
     * Creates new form statistics
     */
    public statistics() {
            initComponents();
            this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        stdInfoBtn = new javax.swing.JButton();
        issueDtlsBtn = new javax.swing.JButton();
        bkDtlsBtn = new javax.swing.JButton();
        rtnDtlsBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        backBtn.setText("BACK");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 60));

        stdInfoBtn.setBackground(new java.awt.Color(204, 204, 204));
        stdInfoBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stdInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinfo.png"))); // NOI18N
        stdInfoBtn.setText("STUDENT INFO");
        stdInfoBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stdInfoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stdInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdInfoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(stdInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 310, 150));

        issueDtlsBtn.setBackground(new java.awt.Color(204, 204, 204));
        issueDtlsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        issueDtlsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issuedetails.jpg"))); // NOI18N
        issueDtlsBtn.setText("ISSUE DETAILS");
        issueDtlsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        issueDtlsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        issueDtlsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueDtlsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(issueDtlsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 320, 150));

        bkDtlsBtn.setBackground(new java.awt.Color(204, 204, 204));
        bkDtlsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bkDtlsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookdetails.png"))); // NOI18N
        bkDtlsBtn.setText("BOOK DETAILS");
        bkDtlsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bkDtlsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkDtlsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkDtlsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bkDtlsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 310, 150));

        rtnDtlsBtn.setBackground(new java.awt.Color(204, 204, 204));
        rtnDtlsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtnDtlsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/returndetails.png"))); // NOI18N
        rtnDtlsBtn.setText("RETURN DETAILS");
        rtnDtlsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rtnDtlsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rtnDtlsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtnDtlsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rtnDtlsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 320, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/statistic.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 1400, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        new menupage().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
     
    }//GEN-LAST:event_formComponentShown

    private void stdInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdInfoBtnActionPerformed
        setVisible(false);
        new studentInfo().setVisible(true);
    }//GEN-LAST:event_stdInfoBtnActionPerformed

    private void bkDtlsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkDtlsBtnActionPerformed
        setVisible(false);
        new bookDetails().setVisible(true);
        
    }//GEN-LAST:event_bkDtlsBtnActionPerformed

    private void issueDtlsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueDtlsBtnActionPerformed
         setVisible(false);
        new issueDetails().setVisible(true);
    }//GEN-LAST:event_issueDtlsBtnActionPerformed

    private void rtnDtlsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtnDtlsBtnActionPerformed
         setVisible(false);
        new returnDetails().setVisible(true);
    }//GEN-LAST:event_rtnDtlsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bkDtlsBtn;
    private javax.swing.JButton issueDtlsBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton rtnDtlsBtn;
    private javax.swing.JButton stdInfoBtn;
    // End of variables declaration//GEN-END:variables
}
